platform :ios, "13.0"
use_frameworks! :linkage => :static
install! 'cocoapods', :warn_for_unused_master_specs_repo => false

target 'JSNestedScrollExample' do
  pod "JSNestedScroll", :path => ".."

  pod "QMUIKit"
  pod "SnapKit"
  pod "Then"
  pod "MJRefresh"
  pod 'SwiftLint', :configurations => ['Debug']
  pod "LookInsideServer", :git => "https://github.com/LookInsideApp/LookInside-Release.git", :tag => "0.2.7", :configurations => ['Debug']
end
