install! 'cocoapods', :warn_for_unused_master_specs_repo => false
platform :ios, "11.0"
use_frameworks! :linkage => :static

target 'JSNestedScrollExample' do
  pod "JSNestedScroll", :path => ".."

  pod "QMUIKit"
  pod "SnapKit", "~> 5.6.0"
  pod "LookinServer", :subspecs => ['Swift'], :configurations => ["Debug"]
  pod "Then", "~> 3.0.0"
  pod "MJRefresh", "~> 3.7.5"
end